from client import Client
from account import Account
client1 = Client("C001", "zhijianhuang", "a1979239@adelaide.edu.au")
print(client1.name)
print(client1.contact)
client1.update_contact("2531553681@qq.com")
print(client1.contact)

account1 = Account("A001", "Saving", 1000)
print(account1.balance)
account1.deposit(500)
print(account1.balance)
account1.withdraw(200)
print(account1.balance)
account1.withdraw(2000)  #if not enough
client2 = Client("C002", "xiaoyu li", "xiaoyu.li@example.com")
client3 = Client("C003", "aki", "aki@example.com")
print(client2.name)
print(client3.name)
print(client2.contact)
client2.update_contact("zhijianhuang@gmail.com")
print(client2.contact)
account2 = Account("A002", "Checking", 2000)
account3 = Account("A003", "Saving", 3000)

print(account2.balance)
print(account3.balance)
account2.deposit(1000)
print(account2.balance)
account3.withdraw(500)
print(account3.balance)
print(account1.balance)
print(account2.balance)
account1.deposit(300)
print(account1.balance)
print(account2.balance)